### ISSUE TITLE
can not skip to some specific page--https://explorer.nebulas.io/#/accounts?p=1

### ISSUE THREAD

**Issue by jasonfengzs** [nebulasio/explorer#21]
can not skip to some specific page.

**Comment by wangzimei** [comment]
did you mean it should add a text box, when enter some number and hit enter, navigate to that page?

**Comment by jasonfengzs** [comment]
yes.发自我的iPhone------------------ Original ------------------From: wangzimei  <notifications@github.com>Date: Mon,Mar 19,2018 8:08 PMTo: nebulasio/explorer <explorer@noreply.github.com>Cc: jasonfengzs <fengzusheng@126.com>, Author <author@noreply.github.com>Subject: Re: [nebulasio/explorer] can not skip to some specificpage--https://explorer.nebulas.io/#/accounts?p=1 (#21)did you mean it should add a text box, when enter some number and hit enter, navigate to that page?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nebulasio/explorer","title":"nebulasio/explorer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nebulasio/explorer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wangzimei in #21: did you mean it should add a text box, when enter some number and hit enter, navigate to that page?"}],"action":{"name":"View Issue","url":"https://github.com/nebulasio/explorer/issues/21#issuecomment-374190494"}}}

**Comment by wangzimei** [comment]
confirmed, will do
