### ISSUE TITLE
[UI]search bar need a placeholder attr

### ISSUE THREAD

**Issue by vincik** [nebulasio/explorer#24]
look like `<input type="text" placeholder="Only address,not Txid" />`

**Comment by raphaelfeng** [comment]
Currently, it does have a placeholder attr with value "Search".
> \<input type="search" placeholder="Search" class="form-control mr-sm-2"\>

But searching by tx is not working right now, so will file an issue for searching by tx.

**Comment by raphaelfeng** [comment]
@vincik I will close this issue and free feel to reopen and add more details if https://github.com/nebulasio/explorer/issues/25 does not fix what you meant.
