### ISSUE TITLE
Search by tx hash does not work

### ISSUE THREAD

**Issue by raphaelfeng** [nebulasio/explorer#25]
Try searching any tx hash in the search box and no transaction is returned.
The search http request return 500.
But in [RpcController](https://github.com/nebulasio/explorer/blob/d053de6b79fed90db1c0064a6e10f60d0cac012e/explorer-backend/src/main/java/io/nebulas/explorer/controller/RpcController.java)'s search method, it is querying the transaction too, so it should be able to support search by tx hash.

**Comment by 15010159959** [comment]
fixed
