### ISSUE TITLE
Show `Coinbase` of block in block detail page

### ISSUE THREAD

**Issue by fbzhong** [nebulasio/explorer#26]
In Nebulas, the `Coinbase` is the address receiving the reward and gas, are defined in `https://github.com/nebulasio/go-nebulas/blob/develop/core/pb/block.proto`

In the block detail page, the `coinbase` does not displayed, I think we should display it.
https://explorer.nebulas.io/#/block/1064614

**Comment by 15010159959** [comment]
fixed
