### ISSUE TITLE
Add a expiry time for `pending tx`

### ISSUE THREAD

**Issue by fbzhong** [nebulasio/explorer#27]
The lifecycle of a tx is:
`created -> pending -> packed in block or reject from LRU cache`

So it's not easy to identify whether a `pending tx` is pending or not. So, I'd suggest we add `expiry time` in Explorer to auto cleanup `expired pending tx`.

The value of `expiry` could be 48h for production, 1h for development.

**Comment by wanghn** [comment]
view commit [b9171fc](https://github.com/nebulasio/explorer/commit/b9171fc8b54e103a344b40e1c0e6d81ca14ee1bf)

**Comment by fbzhong** [comment]
Awesome, good job!
