### ISSUE TITLE
Directly linking to tx routes user to 404 page

### ISSUE THREAD

**Issue by CodyMorris** [nebulasio/explorer#28]
Hey guys - looking to start contributing to this project.  Yes, I believe....

Anyway, the block explorer will 404 if you try to visit a transaction ID directly, in a new tab.

Repro steps: right click this url and click 'open in new tab'

https://explorer.nebulas.io/#/tx/04f37719b8f00b70a0b20b4127770d113b8780772739b2617c031c21fd2198ff

that is the txID of the genesis transaction that has the manifesto.  Seems like theres some routing issues going on.  Side note - do you guys need help making a more "nebulas" 404 page?  this one is very 90's

Thanks for the hard work

**Comment by wanghn** [comment]
@CodyMorris where did you get this txID, I search nebulas mainnet and testnet,  can not find this txID, so it indeed should go to "404 page"

**Comment by fbzhong** [comment]
@wanghn this txid does exist, is the tx inside genesis block of mainnet:
https://explorer.nebulas.io/#/tx/04f37719b8f00b70a0b20b4127770d113b8780772739b2617c031c21fd2198ff

**Comment by wangzimei** [comment]
when sessionStorage.apiType is missing, there are 2 places that will use their own default api prefix
- in header.vue
- in api.js
which is bad. This should be only 1 place to set default api prefix

This is fixed by moving all possible api prefixes to assets/app-config.js and setting the default only in index.js

**Comment by wangzimei** [comment]
@CodyMorris thanks for reporting! in regard to better 404 page, would you mind upload an image file  or something to demonstrate the idea?

**Comment by CodyMorris** [comment]
You're welcome @wangzimei - I'll whip up something a little later today and submit it separately as an enhancement tagged issue
