### ISSUE TITLE
Mobile issue and make final balance readable 

### ISSUE THREAD

**Issue by bachvtuan** [nebulasio/explorer#31]
Here is mobile issue when you zoom out 
![screenshot_2018-04-28-21-51-06-602_com android chrome](https://user-images.githubusercontent.com/2065400/39397773-d97eaee0-4b2e-11e8-91cd-b0284066f33d.png)

And this address has a lot of nas but currently its balance is hard to figure out how much nas 
![img_20180428_215321](https://user-images.githubusercontent.com/2065400/39397789-15a24288-4b2f-11e8-9ea2-4bc3916c7fee.jpg)

**Comment by wanghn** [comment]
It is fixed
