### ISSUE TITLE
Can't find NAS account using Explorer

### ISSUE THREAD

**Issue by levipage** [nebulasio/explorer#32]
I created a new NAS wallet using the web wallet download. I can't find my address using the explorer.

I see two issues:
1) There is no search function to allow me to enter my address and search.
2) My only option is to click on an existing address and change the URL to use my public address instead. This isn't good usability. However, I get a page not found error.

I would expect that I could visit: https://explorer.nebulas.io/#/address/myaddress
But... This does not work. This gives me a 404 error. Do I need to make a deposit to the address before it will show as valid? This is not the behavior that I would expect.

**Comment by smartpunter** [comment]
Same issue here.
Also, when searching valid address in explorer, it says 'oops'.

**Comment by hostgame** [comment]
Same issue
Address https://explorer.nebulas.io/#/testnet/address/n1ZZfZAVHFpyZZedAwN1664irKi7vaMNtZA
and it has balance. I checked here https://testnet.nebulas.io/claim/

**Comment by Nufflee** [comment]
Same here, this is a pretty serious issue because I don't even know if my account is valid or not, we need to get developers' eyes onto this. My address: n1NmQoV2349d3jp2TJoDDZbdErGFM5X331E.

**Comment by Nufflee** [comment]
cc @wanghn @15010159959 @ideaalloc

**Comment by Nufflee** [comment]
Seems fixed! https://explorer.nebulas.io/#/address/n1NmQoV2349d3jp2TJoDDZbdErGFM5X331E works now.

**Comment by levipage** [comment]
Still not working for me, so issue is still not fixed.

**Comment by levipage** [comment]
@15010159959 Can you clarify if this means the wallet address is invalid, or is this just an issue with the explorer? I am afraid to send funds to this address.

**Comment by wanghn** [comment]
@levipage what is your account address?
This issue has been fixed, before explorer only display account which have transactions, now we have changed display logic, as long as the account address is correct, it will be displayed after search

**Comment by levipage** [comment]
@wanghn My address works fine now, but I sent money to it earlier -- and, as you mentioned it starting working once it had some transactions. Sounds like you resolved the problem though! 

Also it appears that the search box is now working with my address! Great work team!
