### ISSUE TITLE
Wallet balance is shown in WEI, instead of NAS

### ISSUE THREAD

**Issue by smartpunter** [nebulasio/explorer#33]
The wallet balances must be shown in NAS, WEI should be used only for gas.
Right now it is completely unreadable:
https://explorer.nebulas.io/#/address/n1HjnjfY7W9GxbRqT4tfr56rd8Kxh8rMA7L
NAS Balance: | 1.54994289999984e+24 Wei

**Comment by 15010159959** [comment]
Received your question and is making changes

**Comment by wanghn** [comment]
it is fixed.
