### ISSUE TITLE
输入钱包地址无法查到交易记录

### ISSUE THREAD

**Issue by zhaocongliang** [nebulasio/explorer#34]
在测试网部署合约之后，输入钱包地址无法查到交易记录？

**Comment by fzlalxcndr** [comment]
???what

**Comment by zhaocongliang** [comment]
I deploy my contract  in the test network  ,when I enter the wallet address in [https://explorer.nebulas.io/](https://explorer.nebulas.io/ ),I can not find the transaction records.

**Comment by 15010159959** [comment]
正在抓紧修复，

**Comment by fzxa** [comment]
Bug has been repaired . thx
