### ISSUE TITLE
未被确认的异常交易

### ISSUE THREAD

**Issue by dd233** [nebulasio/explorer#35]
![image](https://user-images.githubusercontent.com/33377207/39753728-6498d12a-52f2-11e8-9637-85510526405c.png)

![image](https://user-images.githubusercontent.com/33377207/39753745-734c170e-52f2-11e8-8b09-90dd5c75ba00.png)

这是什么情况，属于某种bug吗？

**Comment by wanghn** [comment]
不属于bug，但现在已经优化了。
在之前版本中如果是交易属于异常的交易，explorer是不知道的，只能通过交易超时上链来移除交易，但现在在subscribe事件中增添了异常交易的remove通知，可以跟go-nebulas保持一致了
