### ISSUE TITLE
time ago calc bug

### ISSUE THREAD

**Issue by act262** [nebulasio/explorer#43]
`timeConversion(Date.now() - tx.timestamp) `计算时间这里是直接取本地时间对比的，但是不同电脑时间可能不一样就会导致计算结果异常。

貌似应该用接口返回数据中的`currentTimestamp`字段去对比时间差
即`timeConversion(currentTimestamp - tx.timestamp) `

原代码位置： tx.vue     txs.vue
> <td>{{ timeConversion(Date.now() - tx.timestamp) }} ago ({{ new Date(tx.timestamp).toString() }} | {{ tx.timestamp }})

<img width="679" alt="bufg" src="https://user-images.githubusercontent.com/4591669/40180912-7ecd1cf2-5a1a-11e8-81ba-d5045340df0a.png">

**Comment by fzxa** [comment]
感谢指正， 我们会在服务端增加时间判断解决

**Comment by fzxa** [comment]
@act262 已经解决了
