### ISSUE TITLE
No scroll bar to find in the explorer

### ISSUE THREAD

**Issue by saina110** [nebulasio/explorer#47]
This is my first time to enter the NAS explorer, but unfortunately I cannot find the scroll bar to continue to view the rest of the information in the bottom of the web page, I'm not sure whether it is the bug in some condition, hope developer could fix this issue

**Comment by rutkat** [comment]
@saina110 What device and browser are you using? The scrolling works for me on a mac using Chrome, although mobile widths could be optimized.

**Comment by saina110** [comment]
Hello rutkat,

I login today and it works ok for me now, I can scroll up and down to check the information in the explorer. I use chrome in mac. I will close this issue.

Thank you
