### ISSUE TITLE
Transfers Failed in Nebulas Blockchain

### ISSUE THREAD

**Issue by wagnermangolin** [nebulasio/explorer#58]
Who will solve this? Or am I going to lose my coins?

Failed Transfer 1:
https://explorer.nebulas.io/#/tx/de5a5bcdbf934558942cfc8469c2b6f86a5d5af42e81b9d0dcf759fd923bd4ab

Failed Transfer 2:
https://explorer.nebulas.io/#/tx/6de3f701e8881e8bee2fec3c4c021eef2d63f1ef86491429b0618a3a50e07505

**Comment by yupnano** [comment]
That might because there is something wrong in your transaction, such as zero balance, low gasPrice & gasLimit, improper nonce.
Please paste your transaction details here.

https://github.com/nebulasio/neb.py/issues/5#

**Comment by yupnano** [comment]
https://github.com/nebulasio/explorer/issues/64#
