### ISSUE TITLE
Build-Error

### ISSUE THREAD

**Issue by mockchain** [nebulasio/explorer#6]
Why i need install such deps:
    "jssha": "^2.3.1",
    "keccak": "^1.4.0",
    "protobufjs": "^6.8.4",
    "scryptsy": "^2.0.0",
    "secp256k1": "^3.5.0",
    "serve-favicon": "~2.4.5",
    "xmlhttprequest": "^1.8.0",
    "bignumber": "^1.1.0"
when i run the nasWallet on master.

**Comment by qywang2012** [comment]
These dependencies not used now, later will change to npm dependency

**Comment by mockchain** [comment]
:)
