### ISSUE TITLE
How to contribute to explorer?

### ISSUE THREAD

**Issue by 5sWind** [nebulasio/explorer#62]
I am running in local front-end environment and editing back-end data.
The result is not shown on expectation.

**Comment by 5sWind** [comment]
I don't know how to modify the data 'type' from api getAccount?

**Comment by ChengOrangeJu** [comment]
Could you help explain more about why you modify the data `type`? It shows the different type of account 87 stands for normal address and 88 stands for contract address

**Comment by ChengOrangeJu** [comment]
https://github.com/nebulasio/wiki/blob/master/rpc.md#getaccountstate

**Comment by 5sWind** [comment]
@ChengOrangeJu I want to modify and output contract address, but api `http://192.168.1.168:8080/api/account` doesn't output variable 'type' as JSON, while the frontend can get type through o.type. it stands 0 and I can't find the original input and modify it.
