### ISSUE TITLE
gas limit

### ISSUE THREAD

**Issue by jester21** [nebulasio/explorer#64]
how can i get more gas?

https://explorer.nebulas.io/#/tx/fbf222825c9b8ea0cb7224a8901af62d90ff2fb30037c7591dd9080bd954f1ad

**Comment by yupnano** [comment]
with which tool did you send this transaction? NasNano or NasExtWallet?

**Comment by jester21** [comment]
on android wallet

**Comment by yupnano** [comment]
Please wait for next version, it will support gas limit adjust. 
It'll come out soon, maybe next week.
