### ISSUE TITLE
How to connect Locale Nebulas chain

### ISSUE THREAD

**Issue by changqing91** [nebulasio/explorer#68]
where is the config to connect locale nebulas chain

**Comment by catalsdevelop** [comment]
I've make a local node image with dockerfile, you can ref it https://github.com/catalsdevelop/nebulas-node

**Comment by yupnano** [comment]
for the java back-end service, you can just edit the application.yml to connect to your local node:
![image](https://user-images.githubusercontent.com/5012612/44576508-53b99c80-a7c1-11e8-8d1b-f662ab7d3a81.png)
 and your local MySql:
![image](https://user-images.githubusercontent.com/5012612/44576596-8368a480-a7c1-11e8-8089-61e51f211249.png)

**Comment by Samuelchen85** [comment]
No response afterwards, assuming this was fixed.
