### ISSUE TITLE
主网账号的nas数据是不是有问题？

### ISSUE THREAD

**Issue by lrl219** [nebulasio/explorer#69]
数据非常不正常，前20名的账户nas持仓数9000多w个，看是否展示有误？
![image](https://user-images.githubusercontent.com/5787117/43587685-5e8f3e92-969d-11e8-9c04-f0ee6fad8bf0.png)

**Comment by gitmakenoise** [comment]
请问NAS有提供区块浏览器API吗，比如获取某个地址的交易记录

**Comment by Samuelchen85** [comment]
@lrl219 这个是没问题的，请参考我们主网代码中的配置文件genesis.conf，我们预设有20个地址，每个地址持有500万NAS。而且这不是星云独有的，其他项目也是如此。

@gitmakenoise 我们目前并没有对外提供explorer的API，已在 #76 回复你了。
