### ISSUE TITLE
Proposal: clean up explorer-front/readme.md

### ISSUE THREAD

**Issue by 1c7** [nebulasio/explorer#72]
## please clean it up  
https://github.com/nebulasio/explorer/blob/develop/explorer-front/readme.md

![image](https://user-images.githubusercontent.com/1804755/44308705-22ba2000-a3ed-11e8-93d2-5462e41bbe41.png)

![image](https://user-images.githubusercontent.com/1804755/44308725-585f0900-a3ed-11e8-8795-d7dccc581eea.png)

**Comment by yuzhouwww** [comment]
Thanks for your proposal, the cleaning up work is done. https://github.com/nebulasio/explorer/commit/a2f9ad461f29e1c197fceca7e9384fd3f0c8ad4f
